electron/release-status

.github/workflows/release-calendar-events.yml

This is being migrated from https://github.com/electron/private-workflows/commits/main/.github/workflows/release-calendar-events.yml to this repo so that it can live somewhere public.

ci: generate release calendar events for an Electron major

---

.github/workflows/audit-chromium-schedule-dates.yml

Being migrated from https://github.com/electron/private-workflows/commits/main/.github/workflows/audit-chromium-schedule-dates.yml to be somewhere publicly visible.
Draft until we populate the `CHROMIUM_DATES_SLACK_WEBHOOK_URL` secret.

ci: audit to watch for changes to Chromium schedule

---

src/views/pr.handlebars

Refs the functional code further down in the file:
https://github.com/electron/release-status/blob/6718e2627b614fca0bc96f48f9778ba45de8f9ba/src/views/pr.handlebars#L35

fix: add 'v' prefix to primary release version on PR lookup

---

src/views/pr-lookup.handlebars

Currently typing a PR number into the lookup form and hitting enter does nothing, which is unintuitive. Fixes that by making it act as expected, and I threw in a `required` on the input field as well.

fix: submit PR lookup form on enter

---

package.json
src/data.js

Should be able to use builtin `fetch`. Sets the minimum Node.js engine as well, to be safe.

chore: remove node-fetch usage

---

package.json
yarn.lock

Clears a security warning regarding `send`.

build(deps): bump express to clear audit

---

.github/workflows/audit-releases-json.yml

Audits https://electronjs.org/headers/index.json to check for any missing releases.
~~Needs `RELEASES_JSON_SLACK_WEBHOOK_URL` to be populated before merging.~~

ci: audit releases JSON for missing releases

---

src/data.js

Follow-up to #69 which inadvertently broke authentication. Unfortunately this call site uses `name` for the repo name, rather than `repo` like some other call sites.

fix: restore get auth options repo name

---

src/data.js

Follow-up to #69, this extra exclamation mark slipped in during a refactor.

fix: exclude bot PRs from recent PRs

---

src/views/layouts/main.handlebars

This PR Fixes: https://github.com/electron/release-status/issues/94 (invalid shortcut-url in header).
Updated the favicon.ico to new url from electron official website
I have closed previous PR, due to some disturbance it was making on my side.

fix: correct favicon URL

---

src/routes/releases.js

This PR Fixes: #97 (wrong display of versions on releases page)
updated the condition to handle 0 value for major, which was being treated as false value.

fix: handle 0.x version selection

---

package.json

This PR updates the `postinstall` script in `package.json` to use Node.js’s built-in `fs.cpSync` instead of the Unix-specific `cp` command, ensuring cross-platform compatibility without external dependencies, as requested by @erickzhao.
- Changed postinstall to use fs.cpSync as requested: `node -e 'fs.cpSync("./node_modules/prismjs/themes/", "./src/static/css/prismjs/", { recursive: true })'`.
- Restored yarn.lock to match upstream/main to avoid unintended changes.
- Tested on Windows 11 with Node.js 22.14.0.

build: update postinstall script to work cross-platform

---

app/redirects/release-build.tsx
app/redirects/releases.tsx
app/routes.ts

Fixes an issue that @dsanders11 noted where some old URLs weren't quite the same, this leaves the new URLs as "correct" and just redirects the old ones

fix: redirect legacy routes to new releases routes

---

app/components/ReleaseTable.tsx

Makes all the numbers align across versions by fixing widths for certain columns. This only applies to the largest viewports, and smaller ones default to being responsive.
| Before | After |
|--------|-------|
| ![image](https://github.com/user-attachments/assets/e81daff4-1c90-47df-84bb-6e90e9e62fa1) | ![image](https://github.com/user-attachments/assets/fafd607e-f026-4713-9f8a-c0a5f068a483) |

style: align release table columns

---

app/routes/history.tsx

Fixes the nightly percentage for the current month so that we only count days that have elapsed so far for the calculation.
| Before | After |
|--------|-------|
| ![image](https://github.com/user-attachments/assets/c961dd82-104f-4e16-baf3-110ca3ba4020)| ![image](https://github.com/user-attachments/assets/6936a66d-0658-403b-a19b-aec0501404d6) |

fix(history): correct nightly percentage for current month

---

app/routes/release/single.tsx

We've been recommending people install Electron as a devDependency for a while in our docs, so this aligns the installation commands for each release in accordance.

fix: recommend devDeps for package install

---

app/routes/build/release-job.tsx
app/routes/history.tsx
app/routes/history/date.tsx
app/routes/pr/details.tsx
app/routes/pr/lookup.tsx
app/routes/release/all.tsx
app/routes/release/compare.tsx
app/routes/release/single.tsx

This follows what we do on electronjs.org by suffixing all page titles with `| Electron Releases`.
I think it makes having multiple tabs of the website easier to distinguish at a glance since we're not starting each page title with "Electron".

chore: standardize title meta tags

---

app/routes/release/all.tsx

This PR handles the condition when major is set to `v0` by allowing major to be 0 and checking for `null` value only.
Before:
After:

fix: handle case for v0 releases

---

app/components/Select.tsx
app/routes/build/release-job.tsx
app/routes/history.tsx
app/routes/release/compare.tsx

Adds some missing `cacheControl` values so that loader values are correctly cached when preloaded client side. Also adds manual instrumentation for other-year prefetching based on the select on the `History` page.

fix: make history pages switch faster

---

app/components/Pagination.tsx

This PR solves overflow for `Pagination Component` by changing css for small screens. Somewhat related to #156 
**Before:**
**After:**

Fix: overflow in pagination component
